// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp68_T1wWuWTnHG1__NNTOI7LSK-f2wf4',
    appId: '1:1069904533422:web:a7bfff76038cbb29aada3f',
    messagingSenderId: '1069904533422',
    projectId: 'maddemo-ab2bf',
    authDomain: 'maddemo-ab2bf.firebaseapp.com',
    storageBucket: 'maddemo-ab2bf.firebasestorage.app',
    measurementId: 'G-3V3TCFMSMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbJUP2M34P5iQKpY-yJmzpwRWp1Fd1oak',
    appId: '1:1069904533422:android:e0705a1d31d687e5aada3f',
    messagingSenderId: '1069904533422',
    projectId: 'maddemo-ab2bf',
    storageBucket: 'maddemo-ab2bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxVsJVV7FrEIZsSjlcwDg-fPcs0FBJWrA',
    appId: '1:1069904533422:ios:532c1a2b0e2f8081aada3f',
    messagingSenderId: '1069904533422',
    projectId: 'maddemo-ab2bf',
    storageBucket: 'maddemo-ab2bf.firebasestorage.app',
    iosBundleId: 'com.example.gift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxVsJVV7FrEIZsSjlcwDg-fPcs0FBJWrA',
    appId: '1:1069904533422:ios:532c1a2b0e2f8081aada3f',
    messagingSenderId: '1069904533422',
    projectId: 'maddemo-ab2bf',
    storageBucket: 'maddemo-ab2bf.firebasestorage.app',
    iosBundleId: 'com.example.gift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp68_T1wWuWTnHG1__NNTOI7LSK-f2wf4',
    appId: '1:1069904533422:web:763d3fcc0665d748aada3f',
    messagingSenderId: '1069904533422',
    projectId: 'maddemo-ab2bf',
    authDomain: 'maddemo-ab2bf.firebaseapp.com',
    storageBucket: 'maddemo-ab2bf.firebasestorage.app',
    measurementId: 'G-9RZMBW1Z77',
  );
}
